# Generated by Django 4.0.5 on 2022-06-17 20:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='health_tell',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='hood_logo',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='police_number',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health_telephone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_pic',
            field=cloudinary.models.CloudinaryField(default=0, max_length=255, verbose_name='images'),
            preserve_default=False,
        ),
    ]
